FROM node:16

WORKDIR /app

RUN npx create-react-app react_comment_app \
    && npm install axios \
    && npm install react-router-dom

WORKDIR /app/react_comment_app

CMD [ "npm", "start" ]

# プロジェクトとは直接関係がないがこのファイルのステージング状態が消えない
