FROM python:3.11

WORKDIR /code

COPY ./api/requirements.txt /code/

RUN pip install --upgrade pip\
    && pip install --break-system-packages -r requirements.txt

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]